export const strings = {
  brandName: 'EASYBRANDS',
  homeTitle: 'Home',
  searchPlaceholder: 'Search products',
  searchAccessibilityLabel: 'Search products',
  shopByCategory: 'Shop by Category',
  newArrivals: 'New Arrivals',
  newArrivalsLabel: 'NEW',
  discountBadge: 'OFF',
  priceUnavailable: 'Price on request',
  ratingSymbol: '★',
  errorTitle: "We couldn't load your feed.",
  errorMessage: 'Check your connection and try again.',
  errorCta: 'TRY AGAIN',
  emptyTitle: 'Nothing here yet',
  emptyMessage: 'New arrivals are on the way.',
  emptyCta: 'REFRESH',
  categoryEmptyTitle: 'No products in this category',
  categoryEmptyMessage: 'This category has nothing in stock right now. Try another one.',
  categoryLoading: 'Loading products',
  productCountLabel: 'products',
  loadingMore: 'Loading more products',
  filterTitle: 'Filter & Sort',
  filterButton: 'Filter',
  filterBrand: 'Brand',
  filterPrice: 'Price',
  filterMinPrice: 'Min',
  filterMaxPrice: 'Max',
  filterSort: 'Sort by',
  filterApply: 'APPLY',
  filterClear: 'Clear all',
  filterClose: 'Close filters',
  sortPriceAsc: 'Price: low to high',
  sortPriceDesc: 'Price: high to low',
  sortNameAsc: 'Name: A to Z',
  filterInvalidPrice: 'Enter a valid number',
  filterPriceSwapped: 'Min was above max, so they were swapped',
  filterBrandsUnavailable: 'Brands could not be loaded',
  filterEmptyTitle: 'No matching products',
  filterEmptyMessage: 'Try removing a filter or widening your price range',
  filterMinPriceA11y: 'Minimum price',
  filterMaxPriceA11y: 'Maximum price',
};