export const strings = {
  brandName: 'EASYBRANDS',
  homeTitle: 'Home',
  searchPlaceholder: 'Search products',
  searchAccessibilityLabel: 'Search products',
  searchTitle: 'Search',
  searchClear: 'Clear',
  searchClearLabel: 'Clear search',
  searchPrompt: 'Search by product, brand or style. Try "lawn suit" or "Limelight".',
  searchEmptyTitle: 'No matches',
  searchEmptyMessage: 'Nothing matched that search. Try a shorter phrase or a different spelling.',
  searchErrorTitle: "We couldn't run that search.",
  searchErrorMessage: 'Check your connection and try again.',
  searchUpdating: 'Updating results…',
  searchEndOfResults: "That's everything for this search.",
  searchResultsLabel: (total: number): string => `${total} search results`,
  shopByCategory: 'Shop by Category',
  newArrivals: 'New Arrivals',
  newArrivalsLabel: 'NEW',
  discountBadge: 'OFF',
  priceUnavailable: 'Price on request',
  ratingSymbol: '★',
  errorTitle: "We couldn't load your feed.",
  errorMessage: 'Check your connection and try again.',
  errorCta: 'TRY AGAIN',
  emptyTitle: 'Nothing here yet',
  emptyMessage: 'New arrivals are on the way.',
  emptyCta: 'REFRESH',
  categoryEmptyTitle: 'No products in this category',
  categoryEmptyMessage: 'This category has nothing in stock right now. Try another one.',
  categoryLoading: 'Loading products',
  productCountLabel: 'products',
  loadingMore: 'Loading more products',
  filterTitle: 'Filter & Sort',
  filterButton: 'Filter',
  filterBrand: 'Brand',
  filterPrice: 'Price',
  filterMinPrice: 'Min',
  filterMaxPrice: 'Max',
  filterSort: 'Sort by',
  filterApply: 'APPLY',
  filterClear: 'Clear all',
  filterClose: 'Close filters',
  sortPriceAsc: 'Price: low to high',
  sortPriceDesc: 'Price: high to low',
  sortNameAsc: 'Name: A to Z',
  filterInvalidPrice: 'Enter a valid number',
  filterPriceSwapped: 'Min was above max, so they were swapped',
  filterBrandsUnavailable: 'Brands could not be loaded',
  filterEmptyTitle: 'No matching products',
  filterEmptyMessage: 'Try removing a filter or widening your price range',
  filterMinPriceA11y: 'Minimum price',
  filterMaxPriceA11y: 'Maximum price',

  productDetailsTitle: 'Product',
  productBrandLabel: (brand: string): string => `View all products by ${brand}`,
  brandTitle: 'Brand',
  brandProductCount: (total: number): string =>
    total === 1 ? '1 product in stock' : `${total} products in stock`,
  brandResultsLabel: (brand: string): string => `Products by ${brand}`,
  brandEmptyTitle: 'Nothing in stock right now',
  brandEmptyMessage: 'This brand has no in-stock products at the moment. Check back soon.',
  brandEmptyCta: 'Go back',
  brandErrorTitle: "We couldn't load this brand.",
  brandEndOfResults: "That's everything from this brand.",
  brandCategoryAll: 'All',
  brandCategoryLabel: (name: string, count: number): string =>
    `${name}, ${count} ${count === 1 ? 'product' : 'products'}`,
  brandCategoryEmptyTitle: 'Nothing in this category',
  brandCategoryEmptyMessage: 'This brand has nothing in stock in that category. Try another one.',
  brandCategoryEmptyCta: 'Show all',
  productSize: 'Select size',
  productSizeRequired: 'Select a size to continue',
  productSizeUnavailable: 'out of stock',
  productOutOfStock: 'Out of stock',
  productInStock: 'In stock',
  productNoImages: 'No product images available',
  productImageLabel: 'Product image',
  productDescription: 'Details',
  productNoDescription: 'No description provided for this product.',
  productPriceUnavailable: 'Price on request',
  productViewOnBrand: 'View on brand site',
  productOpeningBrand: 'Opening brand site',
  productBrandSiteMissing: 'No brand site link available',
  productSelectSizeFirst: 'Select an available size first',
  productZoomHint: 'Pinch or double tap to zoom',
  productImageFullScreen: 'View image full screen',
};